### ISSUE TITLE
Problems after upgrading to 6.0

### ISSUE THREAD

**Issue by mrfuxi** [TwilioDevEd/client-quickstart-python#2]
Can not place a call:

dial = resp.dial(callerId=os.environ['TWILIO_CALLER_ID'])
TypeError: dial() missing 1 required positional argument: 'number'

**Comment by smendes** [comment]
There was an issue because `VoiceResponse.dial` needs a `number` argument.
It's replaced with `Dial` now which can set either a `number` or a `client`.
